"""updated DB enum Type for permission

Revision ID: fb8c93225035
Revises: 5c509df30880
Create Date: 2025-07-14 15:27:22.322839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb8c93225035'
down_revision: Union[str, Sequence[str], None] = '5c509df30880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

enum_type = "permissionsenum"
new_value = "CAN_VIEW_STATS"

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"ALTER TYPE {enum_type} ADD VALUE IF NOT EXISTS '{new_value}'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
